@startuml
skinparam linetype ortho
"abseil-cpp-dev" --> "abseil-cpp-dev"
"abseil-cpp-dev" --> "so:libabsl_random_internal_randen.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-flags-commandlineflag"
"abseil-cpp-dev" --> "so:libabsl_time_zone.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-flags-internal"
"abseil-cpp-dev" --> "so:libabsl_str_format_internal.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-vlog-config-internal"
"abseil-cpp-dev" --> "so:libabsl_cord_internal.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_flags_usage.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-cordz-info"
"abseil-cpp-dev" --> "so:libabsl_crc_cord_state.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-exponential-biased"
"abseil-cpp-dev" --> "so:libabsl_strings_internal.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_flags_reflection.so.2407.0.0"
"abseil-cpp-dev" --> "so:libc.musl-x86_64.so.1"
"abseil-cpp-dev" --> "abseil-cpp-civil-time"
"abseil-cpp-dev" --> "abseil-cpp-debugging-internal"
"abseil-cpp-dev" --> "so:libabsl_flags_commandlineflag.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-low-level-hash"
"abseil-cpp-dev" --> "so:libabsl_synchronization.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_flags_config.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-raw-hash-set"
"abseil-cpp-dev" --> "abseil-cpp-hash-generator-testing"
"abseil-cpp-dev" --> "so:libabsl_exponential_biased.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-time"
"abseil-cpp-dev" --> "abseil-cpp-time-zone"
"abseil-cpp-dev" --> "pkgconfig"
"abseil-cpp-dev" --> "abseil-cpp-status"
"abseil-cpp-dev" --> "so:libabsl_stacktrace.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_cordz_handle.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-random-internal-randen-hwaes-impl"
"abseil-cpp-dev" --> "abseil-cpp-bad-optional-access"
"abseil-cpp-dev" --> "abseil-cpp-flags-usage"
"abseil-cpp-dev" --> "abseil-cpp-log-globals"
"abseil-cpp-dev" --> "abseil-cpp-hashtablez-sampler"
"abseil-cpp-dev" --> "abseil-cpp-strings"
"abseil-cpp-dev" --> "abseil-cpp-city"
"abseil-cpp-dev" --> "abseil-cpp-symbolize"
"abseil-cpp-dev" --> "abseil-cpp-flags-reflection"
"abseil-cpp-dev" --> "so:libabsl_debugging_internal.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_examine_stack.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-bad-variant-access"
"abseil-cpp-dev" --> "abseil-cpp-crc32c"
"abseil-cpp-dev" --> "abseil-cpp-flags-marshalling"
"abseil-cpp-dev" --> "abseil-cpp"
"abseil-cpp-dev" --> "so:libabsl_raw_logging_internal.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_demangle_rust.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-flags-program-name"
"abseil-cpp-dev" --> "abseil-cpp-leak-check"
"abseil-cpp-dev" --> "so:libstdc++.so.6"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-conditions"
"abseil-cpp-dev" --> "abseil-cpp-flags-commandlineflag-internal"
"abseil-cpp-dev" --> "so:libabsl_strings.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_crc32c.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-log-sink-set"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-globals"
"abseil-cpp-dev" --> "abseil-cpp-raw-logging-internal"
"abseil-cpp-dev" --> "abseil-cpp-log-sink"
"abseil-cpp-dev" --> "abseil-cpp-time-internal-test-util"
"abseil-cpp-dev" --> "abseil-cpp-cord-internal"
"abseil-cpp-dev" --> "abseil-cpp-pow10-helper"
"abseil-cpp-dev" --> "abseil-cpp-bad-any-cast-impl"
"abseil-cpp-dev" --> "abseil-cpp-random-seed-gen-exception"
"abseil-cpp-dev" --> "abseil-cpp-base"
"abseil-cpp-dev" --> "abseil-cpp-random-distributions"
"abseil-cpp-dev" --> "abseil-cpp-flags-parse"
"abseil-cpp-dev" --> "so:libabsl_strerror.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-log-flags"
"abseil-cpp-dev" --> "so:libabsl_random_internal_seed_material.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_random_seed_gen_exception.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-format"
"abseil-cpp-dev" --> "so:libabsl_log_severity.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_flags_usage_internal.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_cordz_functions.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-flags-config"
"abseil-cpp-dev" --> "so:libabsl_base.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-random-internal-randen"
"abseil-cpp-dev" --> "so:libabsl_low_level_hash.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-crc-cord-state"
"abseil-cpp-dev" --> "abseil-cpp-test-instance-tracker"
"abseil-cpp-dev" --> "abseil-cpp-statusor"
"abseil-cpp-dev" --> "abseil-cpp-die-if-null"
"abseil-cpp-dev" --> "so:libabsl_log_internal_proto.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-random-seed-sequences"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-message"
"abseil-cpp-dev" --> "abseil-cpp-string-view"
"abseil-cpp-dev" --> "so:libabsl_log_sink.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-test-actions"
"abseil-cpp-dev" --> "abseil-cpp-cord"
"abseil-cpp-dev" --> "abseil-cpp-demangle-internal"
"abseil-cpp-dev" --> "abseil-cpp-random-internal-distribution-test-util"
"abseil-cpp-dev" --> "abseil-cpp-stacktrace"
"abseil-cpp-dev" --> "so:libgtest.so.1.15.2"
"abseil-cpp-dev" --> "so:libabsl_flags_marshalling.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_log_internal_format.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-exception-safety-testing"
"abseil-cpp-dev" --> "abseil-cpp-examine-stack"
"abseil-cpp-dev" --> "so:libabsl_city.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_random_internal_randen_hwaes.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_flags_commandlineflag_internal.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_time.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_log_internal_fnmatch.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-graphcycles-internal"
"abseil-cpp-dev" --> "so:libabsl_random_internal_randen_hwaes_impl.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-random-internal-randen-hwaes"
"abseil-cpp-dev" --> "so:libabsl_log_internal_test_helpers.so.2407.0.0"
"abseil-cpp-dev" --> "so:libgmock.so.1.15.2"
"abseil-cpp-dev" --> "so:libabsl_log_internal_globals.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-check-op"
"abseil-cpp-dev" --> "abseil-cpp-random-internal-platform"
"abseil-cpp-dev" --> "so:libabsl_log_internal_nullguard.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-strerror"
"abseil-cpp-dev" --> "so:libabsl_spinlock_wait.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_crc_internal.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-test-matchers"
"abseil-cpp-dev" --> "abseil-cpp-random-internal-randen-slow"
"abseil-cpp-dev" --> "abseil-cpp-periodic-sampler"
"abseil-cpp-dev" --> "abseil-cpp-flags-private-handle-accessor"
"abseil-cpp-dev" --> "so:libabsl_int128.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_random_internal_pool_urbg.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-malloc-internal"
"abseil-cpp-dev" --> "abseil-cpp-spinlock-test-common"
"abseil-cpp-dev" --> "abseil-cpp-crc-cpu-detect"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-test-helpers"
"abseil-cpp-dev" --> "abseil-cpp-scoped-mock-log"
"abseil-cpp-dev" --> "abseil-cpp-scoped-set-env"
"abseil-cpp-dev" --> "linux-headers"
"abseil-cpp-dev" --> "so:libabsl_log_initialize.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-spinlock-wait"
"abseil-cpp-dev" --> "so:libabsl_cord.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-str-format-internal"
"abseil-cpp-dev" --> "abseil-cpp-synchronization"
"abseil-cpp-dev" --> "abseil-cpp-random-internal-pool-urbg"
"abseil-cpp-dev" --> "abseil-cpp-crc-internal"
"abseil-cpp-dev" --> "so:libabsl_flags_private_handle_accessor.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-failure-signal-handler"
"abseil-cpp-dev" --> "abseil-cpp-stack-consumption"
"abseil-cpp-dev" --> "abseil-cpp-log-initialize"
"abseil-cpp-dev" --> "so:libabsl_log_internal_log_sink_set.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-per-thread-sem-test-common"
"abseil-cpp-dev" --> "so:libabsl_status.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-log-entry"
"abseil-cpp-dev" --> "so:libabsl_log_internal_message.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_kernel_timeout_internal.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-hash"
"abseil-cpp-dev" --> "abseil-cpp-atomic-hook-test-helper"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-nullguard"
"abseil-cpp-dev" --> "so:libabsl_random_internal_platform.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_cordz_info.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_log_globals.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-proto"
"abseil-cpp-dev" --> "abseil-cpp-cordz-handle"
"abseil-cpp-dev" --> "abseil-cpp-strings-internal"
"abseil-cpp-dev" --> "abseil-cpp-random-internal-seed-material"
"abseil-cpp-dev" --> "so:libabsl_vlog_config_internal.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-int128"
"abseil-cpp-dev" --> "so:libabsl_flags_program_name.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-flags-usage-internal"
"abseil-cpp-dev" --> "abseil-cpp-log-severity"
"abseil-cpp-dev" --> "abseil-cpp-log-internal-fnmatch"
"abseil-cpp-dev" --> "so:libabsl_hash.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_random_internal_randen_slow.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_flags_internal.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_raw_hash_set.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-kernel-timeout-internal"
"abseil-cpp-dev" --> "so:libgcc_s.so.1"
"abseil-cpp-dev" --> "so:libabsl_malloc_internal.so.2407.0.0"
"abseil-cpp-dev" --> "so:libabsl_symbolize.so.2407.0.0"
"abseil-cpp-dev" --> "abseil-cpp-throw-delegate"
"abseil-cpp-dev" --> "abseil-cpp-cordz-functions"
"abseil-cpp-dev" --> "abseil-cpp-cordz-sample-token"
@enduml