@startuml
skinparam linetype ortho
class "ncurses-dev" as ncurses-dev {}
"ncurses-dev" as ncurses-dev --> "libformw" as libformw
class "libformw" as libformw {}
"libformw" as libformw --> "ncurses-terminfo-base" as ncurses-terminfo-base
class "ncurses-terminfo-base" as ncurses-terminfo-base {}
"libformw" as libformw --> "so:libc.musl-x86_64.so.1" as so_libc_musl-x86_64_so_1
class "so:libc.musl-x86_64.so.1" as so_libc_musl-x86_64_so_1 {}
"libformw" as libformw --> "so:libncursesw.so.6" as so_libncursesw_so_6
class "so:libncursesw.so.6" as so_libncursesw_so_6 {}
"ncurses-dev" as ncurses-dev --> "libmenuw" as libmenuw
class "libmenuw" as libmenuw {}
"libmenuw" as libmenuw --> "ncurses-terminfo-base" as ncurses-terminfo-base
"libmenuw" as libmenuw --> "so:libc.musl-x86_64.so.1" as so_libc_musl-x86_64_so_1
"libmenuw" as libmenuw --> "so:libncursesw.so.6" as so_libncursesw_so_6
"ncurses-dev" as ncurses-dev --> "libncurses++" as libncurses++
class "libncurses++" as libncurses++ {}
"libncurses++" as libncurses++ --> "ncurses-terminfo-base" as ncurses-terminfo-base
"libncurses++" as libncurses++ --> "so:libc.musl-x86_64.so.1" as so_libc_musl-x86_64_so_1
"libncurses++" as libncurses++ --> "so:libformw.so.6" as so_libformw_so_6
class "so:libformw.so.6" as so_libformw_so_6 {}
"libncurses++" as libncurses++ --> "so:libgcc_s.so.1" as so_libgcc_s_so_1
class "so:libgcc_s.so.1" as so_libgcc_s_so_1 {}
"libncurses++" as libncurses++ --> "so:libmenuw.so.6" as so_libmenuw_so_6
class "so:libmenuw.so.6" as so_libmenuw_so_6 {}
"libncurses++" as libncurses++ --> "so:libncursesw.so.6" as so_libncursesw_so_6
"libncurses++" as libncurses++ --> "so:libpanelw.so.6" as so_libpanelw_so_6
class "so:libpanelw.so.6" as so_libpanelw_so_6 {}
"libncurses++" as libncurses++ --> "so:libstdc++.so.6" as so_libstdc++_so_6
class "so:libstdc++.so.6" as so_libstdc++_so_6 {}
"ncurses-dev" as ncurses-dev --> "libncursesw" as libncursesw
class "libncursesw" as libncursesw {}
"libncursesw" as libncursesw --> "ncurses-terminfo-base" as ncurses-terminfo-base
"libncursesw" as libncursesw --> "so:libc.musl-x86_64.so.1" as so_libc_musl-x86_64_so_1
"ncurses-dev" as ncurses-dev --> "libpanelw" as libpanelw
class "libpanelw" as libpanelw {}
"libpanelw" as libpanelw --> "ncurses-terminfo-base" as ncurses-terminfo-base
"libpanelw" as libpanelw --> "so:libc.musl-x86_64.so.1" as so_libc_musl-x86_64_so_1
"libpanelw" as libpanelw --> "so:libncursesw.so.6" as so_libncursesw_so_6
"ncurses-dev" as ncurses-dev --> "pkgconfig" as pkgconfig
class "pkgconfig" as pkgconfig {}
@enduml